services:
  whisper-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ADMIN_KEY=hofP20MHXVh5ZhI30QXHA_ly_zqG__ktnQtQpwmXnoo
      - CORS_ORIGINS=*
      - CORS_METHODS=*
      - CORS_HEADERS=*
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
